kind: pipeline
name: default

steps:

  - name: Install
    image: python
    environment:
      PUTIO_USER:
        from_secret: PUTIO_USER
      PUTIO_PASS:
        from_secret: PUTIO_PASS
      PUTIO_URL:
        from_secret: PUTIO_URL
    commands:
    - pip install -e .
    - mkdir test_lib
    - putio --username $PUTIO_USER --password $PUTIO_PASS --url $PUTIO_URL --library_path $(pwd) --library_subpath test_lib || ls test_lib

