build_cloud: Docker
image: Linux

install:
    - apt update
    - apt install python3 python3-pip
    - pip3 install -e .

test_script:
    - mkdir test_lib
    - putio --username $PUTIO_USER --password $PUTIO_PASS --url $PUTIO_URL --library_path $(pwd) --library_subpath test_lib || ls test_lib

build: off
