- name: Publish a Python distribution to PyPI
  if: github.event_name == 'pull_request'
  uses: pypa/gh-action-pypi-publish@master
  with:
    user: __token__
    password: ${{ secrets.pypi_password }}
